alias ls='ls -F'
alias se='setxkbmap -layout se -option ctrl:nocaps'
alias us='setxkbmap -layout us -option ctrl:nocaps'
alias wlanhome='sudo /sbin/ifup wlan0=ghostnet'
alias tmux='TERM=screen-256color tmux'
go_libs="-lm"
go_flags="-g -Wall -include ~/dotfiles/c_here/allheads.h -O3"
alias go_c="c99 -xc '-' $go_libs $go_flags"
